version: 2

sources:
  - name: raw
    description: ""
    database: stock_analytics
    tables:
      - name: raw_company_metadata
        description: ""
        columns:
          - name: ticker
            data_type: varchar
            description: ""
          - name: company_name
            data_type: varchar
            description: ""
          - name: sector
            data_type: varchar
            description: ""
          - name: industry
            data_type: varchar
            description: ""
          - name: country
            data_type: varchar
            description: ""
          - name: exchange
            data_type: varchar
            description: ""
          - name: currency
            data_type: varchar
            description: ""
          - name: market_cap
            data_type: number
            description: ""
          - name: full_time_employees
            data_type: number
            description: ""
          - name: website
            data_type: varchar
            description: ""
          - name: ingested_at
            data_type: timestamp_ntz
            description: ""

      - name: raw_stock_prices
        description: ""
        columns:
          - name: date
            data_type: date
            description: ""
          - name: open
            data_type: float
            description: ""
          - name: high
            data_type: float
            description: ""
          - name: low
            data_type: float
            description: ""
          - name: close
            data_type: float
            description: ""
          - name: volume
            data_type: number
            description: ""
          - name: ticker
            data_type: varchar
            description: ""
          - name: ingested_at
            data_type: timestamp_ntz
            description: ""